2024-01-15 17:07:55,996 INFO    StreamThr :19136 [internal.py:wandb_internal():86] W&B internal server running at pid: 19136, started at: 2024-01-15 17:07:55.996454
2024-01-15 17:07:55,996 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status
2024-01-15 17:07:55,996 INFO    WriterThread:19136 [datastore.py:open_for_write():87] open: C:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\2. Robotics\Y2B-2023-OT2_Twin-main\wandb\run-20240115_170750-vg22q1fb\run-vg22q1fb.wandb
2024-01-15 17:07:55,996 DEBUG   SenderThread:19136 [sender.py:send():382] send: header
2024-01-15 17:07:55,996 DEBUG   SenderThread:19136 [sender.py:send():382] send: run
2024-01-15 17:07:56,411 INFO    SenderThread:19136 [dir_watcher.py:__init__():211] watching files in: C:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\2. Robotics\Y2B-2023-OT2_Twin-main\wandb\run-20240115_170750-vg22q1fb\files
2024-01-15 17:07:56,411 INFO    SenderThread:19136 [sender.py:_start_run_threads():1136] run started: vg22q1fb with start time 1705334875.047864
2024-01-15 17:07:56,414 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: check_version
2024-01-15 17:07:56,414 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: check_version
2024-01-15 17:07:56,474 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: run_start
2024-01-15 17:07:56,489 DEBUG   HandlerThread:19136 [system_info.py:__init__():27] System info init
2024-01-15 17:07:56,490 DEBUG   HandlerThread:19136 [system_info.py:__init__():42] System info init done
2024-01-15 17:07:56,490 INFO    HandlerThread:19136 [system_monitor.py:start():194] Starting system monitor
2024-01-15 17:07:56,490 INFO    SystemMonitor:19136 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-01-15 17:07:56,490 INFO    HandlerThread:19136 [system_monitor.py:probe():214] Collecting system info
2024-01-15 17:07:56,495 INFO    SystemMonitor:19136 [interfaces.py:start():190] Started cpu monitoring
2024-01-15 17:07:56,496 INFO    SystemMonitor:19136 [interfaces.py:start():190] Started disk monitoring
2024-01-15 17:07:56,496 INFO    SystemMonitor:19136 [interfaces.py:start():190] Started gpu monitoring
2024-01-15 17:07:56,496 INFO    SystemMonitor:19136 [interfaces.py:start():190] Started memory monitoring
2024-01-15 17:07:56,499 INFO    SystemMonitor:19136 [interfaces.py:start():190] Started network monitoring
2024-01-15 17:07:57,555 DEBUG   HandlerThread:19136 [system_info.py:probe():151] Probing system
2024-01-15 17:07:57,556 DEBUG   HandlerThread:19136 [system_info.py:_probe_git():136] Probing git
2024-01-15 17:07:57,562 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:07:57,562 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:07:57,627 DEBUG   HandlerThread:19136 [system_info.py:_probe_git():144] Probing git done
2024-01-15 17:07:57,627 DEBUG   HandlerThread:19136 [system_info.py:probe():199] Probing system done
2024-01-15 17:07:57,627 DEBUG   HandlerThread:19136 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22621-SP0', 'python': '3.9.16', 'heartbeatAt': '2024-01-15T16:07:57.555168', 'startedAt': '2024-01-15T16:07:50.465585', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'git': {'remote': 'https://github.com/BredaUniversityADSAI/2023-24b-fai2-adsai-DominikSzewczyk224180.git', 'commit': '7a7443cf755e4e24ab09828c0294df216ba4c505'}, 'email': '112881814+DominikSzewczyk224180@users.noreply.github.com', 'root': 'C:/Users/domin/Desktop/Year 2 Block B/2023-24b-fai2-adsai-DominikSzewczyk224180', 'host': 'MSI', 'username': 'domin', 'executable': 'c:\\Users\\domin\\anaconda3\\envs\\tf\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 2304.0, 'min': 0.0, 'max': 2304.0}, 'cpu_freq_per_core': [{'current': 2304.0, 'min': 0.0, 'max': 2304.0}], 'disk': {'/': {'total': 934.0361289978027, 'used': 605.4400634765625}}, 'gpu': 'NVIDIA GeForce RTX 3050 Ti Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Ti Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 15.708477020263672}}
2024-01-15 17:07:57,627 INFO    HandlerThread:19136 [system_monitor.py:probe():224] Finished collecting system info
2024-01-15 17:07:57,627 INFO    HandlerThread:19136 [system_monitor.py:probe():227] Publishing system info
2024-01-15 17:07:57,627 DEBUG   HandlerThread:19136 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-01-15 17:07:57,631 ERROR   HandlerThread:19136 [system_info.py:_save_conda():219] Error saving conda packages: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "c:\Users\domin\anaconda3\envs\tf\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 215, in _save_conda
    subprocess.call(
  File "c:\Users\domin\anaconda3\envs\tf\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\Users\domin\anaconda3\envs\tf\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\domin\anaconda3\envs\tf\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-01-15 17:07:57,631 DEBUG   HandlerThread:19136 [system_info.py:_save_conda():220] Saving conda packages done
2024-01-15 17:07:57,637 INFO    HandlerThread:19136 [system_monitor.py:probe():229] Finished publishing system info
2024-01-15 17:07:57,637 DEBUG   SenderThread:19136 [sender.py:send():382] send: files
2024-01-15 17:07:57,637 INFO    SenderThread:19136 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-01-15 17:07:57,647 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: python_packages
2024-01-15 17:07:57,647 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: python_packages
2024-01-15 17:07:57,647 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: stop_status
2024-01-15 17:07:57,647 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: stop_status
2024-01-15 17:07:57,647 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-15 17:07:57,647 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: partial_history
2024-01-15 17:07:57,647 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: partial_history
2024-01-15 17:07:57,647 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: partial_history
2024-01-15 17:07:57,647 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: partial_history
2024-01-15 17:07:57,647 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: partial_history
2024-01-15 17:07:57,647 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: partial_history
2024-01-15 17:07:57,647 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: partial_history
2024-01-15 17:07:57,647 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: partial_history
2024-01-15 17:07:57,647 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: partial_history
2024-01-15 17:07:57,647 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: partial_history
2024-01-15 17:07:57,879 DEBUG   SenderThread:19136 [sender.py:send():382] send: telemetry
2024-01-15 17:07:57,879 DEBUG   SenderThread:19136 [sender.py:send():382] send: history
2024-01-15 17:07:57,880 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: summary_record
2024-01-15 17:07:57,885 INFO    SenderThread:19136 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-15 17:07:57,886 DEBUG   SenderThread:19136 [sender.py:send():382] send: history
2024-01-15 17:07:57,886 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: summary_record
2024-01-15 17:07:57,886 INFO    SenderThread:19136 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-15 17:07:57,887 DEBUG   SenderThread:19136 [sender.py:send():382] send: history
2024-01-15 17:07:57,887 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: summary_record
2024-01-15 17:07:57,887 INFO    SenderThread:19136 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-15 17:07:57,888 DEBUG   SenderThread:19136 [sender.py:send():382] send: history
2024-01-15 17:07:57,888 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: summary_record
2024-01-15 17:07:57,888 INFO    SenderThread:19136 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-15 17:07:57,888 DEBUG   SenderThread:19136 [sender.py:send():382] send: history
2024-01-15 17:07:57,888 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: summary_record
2024-01-15 17:07:57,889 INFO    SenderThread:19136 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-15 17:07:57,889 DEBUG   SenderThread:19136 [sender.py:send():382] send: history
2024-01-15 17:07:57,890 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: summary_record
2024-01-15 17:07:57,890 INFO    SenderThread:19136 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-15 17:07:57,891 DEBUG   SenderThread:19136 [sender.py:send():382] send: history
2024-01-15 17:07:57,891 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: summary_record
2024-01-15 17:07:57,891 INFO    SenderThread:19136 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-15 17:07:57,892 DEBUG   SenderThread:19136 [sender.py:send():382] send: history
2024-01-15 17:07:57,892 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: summary_record
2024-01-15 17:07:57,892 INFO    SenderThread:19136 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-15 17:07:57,892 DEBUG   SenderThread:19136 [sender.py:send():382] send: history
2024-01-15 17:07:57,892 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: summary_record
2024-01-15 17:07:57,893 INFO    SenderThread:19136 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-15 17:07:57,893 DEBUG   SenderThread:19136 [sender.py:send():382] send: history
2024-01-15 17:07:57,893 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: summary_record
2024-01-15 17:07:57,893 INFO    SenderThread:19136 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-15 17:07:58,141 INFO    wandb-upload_0:19136 [upload_job.py:push():131] Uploaded file C:\Users\domin\AppData\Local\Temp\tmpgfzdrz3ewandb\dzoa4pux-wandb-metadata.json
2024-01-15 17:07:58,444 INFO    Thread-33 :19136 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\2. Robotics\Y2B-2023-OT2_Twin-main\wandb\run-20240115_170750-vg22q1fb\files\wandb-metadata.json
2024-01-15 17:07:58,444 INFO    Thread-33 :19136 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\2. Robotics\Y2B-2023-OT2_Twin-main\wandb\run-20240115_170750-vg22q1fb\files\conda-environment.yaml
2024-01-15 17:07:58,444 INFO    Thread-33 :19136 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\2. Robotics\Y2B-2023-OT2_Twin-main\wandb\run-20240115_170750-vg22q1fb\files\wandb-summary.json
2024-01-15 17:07:58,444 INFO    Thread-33 :19136 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\2. Robotics\Y2B-2023-OT2_Twin-main\wandb\run-20240115_170750-vg22q1fb\files\requirements.txt
2024-01-15 17:08:00,071 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:00,072 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:01,912 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:08:02,588 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:02,588 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:05,108 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:05,108 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:06,942 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:08:07,616 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:07,616 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:10,130 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:10,130 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:11,965 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:08:12,647 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: stop_status
2024-01-15 17:08:12,647 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: stop_status
2024-01-15 17:08:12,647 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:12,647 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:12,677 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-15 17:08:15,163 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:15,163 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:17,674 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:17,674 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:17,898 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:08:20,196 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:20,196 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:22,717 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:22,717 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:22,935 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:08:25,231 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:25,231 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:27,667 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-15 17:08:27,668 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: stop_status
2024-01-15 17:08:27,668 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: stop_status
2024-01-15 17:08:27,732 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:27,732 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:28,834 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:08:29,754 INFO    Thread-33 :19136 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\2. Robotics\Y2B-2023-OT2_Twin-main\wandb\run-20240115_170750-vg22q1fb\files\config.yaml
2024-01-15 17:08:30,244 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:30,244 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:32,757 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:32,757 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:34,471 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:08:35,311 ERROR   gpu       :19136 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-01-15 17:08:35,321 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:35,321 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:37,841 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:37,841 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:39,527 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:08:40,359 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:40,359 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:42,671 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: stop_status
2024-01-15 17:08:42,671 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-15 17:08:42,671 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: stop_status
2024-01-15 17:08:42,880 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:42,880 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:44,925 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:08:45,404 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:45,404 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:47,924 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:47,924 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:49,964 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:08:50,435 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:50,435 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:52,951 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:52,951 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:54,999 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:08:55,465 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:55,465 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:56,523 DEBUG   SystemMonitor:19136 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-01-15 17:08:56,523 DEBUG   SenderThread:19136 [sender.py:send():382] send: stats
2024-01-15 17:08:57,678 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-15 17:08:57,678 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: stop_status
2024-01-15 17:08:57,678 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: stop_status
2024-01-15 17:08:57,977 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:08:57,977 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:00,487 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:00,487 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:00,850 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:09:03,006 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:03,006 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:05,534 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:05,534 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:05,878 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:09:08,051 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:08,051 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:10,553 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:10,553 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:10,918 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:09:12,692 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: stop_status
2024-01-15 17:09:12,692 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: stop_status
2024-01-15 17:09:12,692 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-15 17:09:13,085 ERROR   gpu       :19136 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-01-15 17:09:13,089 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:13,089 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:15,604 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:15,604 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:16,885 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:09:18,116 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:18,116 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:20,626 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:20,626 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:21,918 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:09:23,135 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:23,135 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:25,639 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:25,639 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:26,538 DEBUG   SenderThread:19136 [sender.py:send():382] send: stats
2024-01-15 17:09:27,550 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:09:27,708 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: stop_status
2024-01-15 17:09:27,708 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-15 17:09:27,708 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: stop_status
2024-01-15 17:09:28,148 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:28,148 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:30,662 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:30,662 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:33,172 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:33,172 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:33,309 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:09:35,690 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:35,690 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:38,215 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:38,215 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:38,353 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:09:40,718 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:40,718 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:42,718 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: stop_status
2024-01-15 17:09:42,718 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: stop_status
2024-01-15 17:09:42,726 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-15 17:09:43,243 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:43,243 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:43,974 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:09:45,757 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:45,757 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:48,273 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:48,273 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:49,001 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:09:50,801 ERROR   gpu       :19136 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-01-15 17:09:50,805 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:50,805 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:53,314 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:53,314 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:54,048 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:09:55,829 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:55,829 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:56,549 DEBUG   SenderThread:19136 [sender.py:send():382] send: stats
2024-01-15 17:09:57,712 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-15 17:09:57,728 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: stop_status
2024-01-15 17:09:57,728 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: stop_status
2024-01-15 17:09:58,346 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:58,347 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:09:59,925 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:10:00,860 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:00,860 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:03,371 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:03,371 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:04,962 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:10:05,878 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:05,882 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:08,403 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:08,403 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:10,003 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:10:10,925 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:10,925 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:12,720 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-15 17:10:12,737 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: stop_status
2024-01-15 17:10:12,737 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: stop_status
2024-01-15 17:10:13,438 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:13,438 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:15,960 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:10:15,973 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:15,973 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:18,481 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:18,486 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:21,000 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:10:21,000 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:21,000 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:23,511 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:23,511 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:26,030 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:26,030 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:26,045 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:10:26,559 DEBUG   SenderThread:19136 [sender.py:send():382] send: stats
2024-01-15 17:10:27,730 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-15 17:10:27,730 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: stop_status
2024-01-15 17:10:27,730 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: stop_status
2024-01-15 17:10:28,563 ERROR   gpu       :19136 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-01-15 17:10:28,573 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:28,573 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:31,089 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:31,089 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:32,002 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:10:33,611 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:33,611 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:36,137 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:36,137 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:37,046 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:10:38,645 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:38,645 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:41,157 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:41,158 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:42,090 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:10:42,745 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-15 17:10:42,745 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: stop_status
2024-01-15 17:10:42,745 DEBUG   SenderThread:19136 [sender.py:send_request():409] send_request: stop_status
2024-01-15 17:10:43,680 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:43,680 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:46,179 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:46,179 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:47,966 DEBUG   HandlerThread:19136 [handler.py:handle_request():146] handle_request: status_report
2024-01-15 17:10:48,687 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-15 17:10:48,687 ERROR   gpu       :19136 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
